apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sf
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-sf
  template:
    metadata:
      labels:
        app: nginx-sf
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.1-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: auth-secret
          mountPath: /etc/nginx/auth
          readOnly: true
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: auth-secret
        secret:
          secretName: auth-basic