apiVersion: v1
kind: Service
metadata:
  name: sf-webserver
  labels:
    app: nginx-sf
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
  selector:
    app: nginx-sf